#!/usr/bin/env python3
"""Export one SSDLite raw-head inference sample as a PS-side C header."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from pc.models.flir_ir_dataset import FlirCocoDetectionDataset
from pc.scripts.verify_ssd_raw_postprocess import (
    load_model,
    pick_device,
    raw_postprocess,
    require_torch_stack,
    run_raw_head,
)


def configure_console_encoding() -> None:
    for stream_name in ("stdout", "stderr"):
        stream = getattr(sys, stream_name, None)
        if stream is not None and hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8", errors="replace")
            except OSError:
                pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export a real SSDLite raw-head sample to C.")
    parser.add_argument("--checkpoint", type=Path, default=Path("build/train_ssdlite_ir_formal/best.pt"))
    parser.add_argument("--manifest", type=Path, default=Path("build/flir_thermal_3cls/dataset_manifest.json"))
    parser.add_argument("--split", choices=("train", "val"), default="val")
    parser.add_argument("--index", type=int, default=0)
    parser.add_argument("--device", type=str, default="auto")
    parser.add_argument("--output-dir", type=Path, default=Path("build/ssd_raw_sample"))
    parser.add_argument(
        "--c-header-out",
        type=Path,
        default=Path("zynq_ps/include/ir_ssd_raw_sample_data.h"),
    )
    parser.add_argument("--score-thresh", type=float, default=None)
    parser.add_argument("--nms-thresh", type=float, default=None)
    parser.add_argument("--detections-per-img", type=int, default=4)
    parser.add_argument("--topk-candidates", type=int, default=100)
    return parser.parse_args()


def c_float_array(name: str, values: list[float], values_per_line: int = 4) -> str:
    def format_c_float(value: float) -> str:
        text = f"{float(value):.9g}"
        if "e" not in text.lower() and "." not in text:
            text += ".0"
        return text + "f"

    lines = [f"static const float {name}[{len(values)}] = {{"]
    for idx in range(0, len(values), values_per_line):
        chunk = values[idx : idx + values_per_line]
        lines.append("    " + ", ".join(format_c_float(value) for value in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def c_u8_array(name: str, values: list[int]) -> str:
    body = ", ".join(f"{int(value)}U" for value in values)
    return f"static const uint8_t {name}[{len(values)}] = {{ {body} }};"


def c_u16_array(name: str, values: list[int]) -> str:
    body = ", ".join(f"{int(value)}U" for value in values)
    return f"static const uint16_t {name}[{len(values)}] = {{ {body} }};"


def round_score_x1000(value: float) -> int:
    score = int(float(value) * 1000.0 + 0.5)
    return max(0, min(score, 1000))


def round_box_coord(value: float, max_value: int) -> int:
    coord = int(float(value) + 0.5)
    return max(0, min(coord, max_value))


def write_header(path: Path, sample: dict[str, Any]) -> None:
    det_count = len(sample["expected_detections"])
    expected_class_ids = [int(item["class_id"]) for item in sample["expected_detections"]]
    expected_scores = [int(item["score_x1000"]) for item in sample["expected_detections"]]
    expected_boxes = []
    for item in sample["expected_detections"]:
        expected_boxes.extend(int(v) for v in item["bbox_xyxy"])

    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(
        [
            "#pragma once",
            "",
            "#include <stdint.h>",
            "",
            "/* Generated by pc/scripts/export_ssd_raw_sample.py. */",
            "/* This is a fixed real-model raw-head sample for PS-side postprocess tests. */",
            "",
            f"#define IRDET_SSD_RAW_SAMPLE_IMAGE_ID             {int(sample['image_id'])}U",
            f"#define IRDET_SSD_RAW_SAMPLE_SOURCE_WIDTH         {int(sample['source_width'])}U",
            f"#define IRDET_SSD_RAW_SAMPLE_SOURCE_HEIGHT        {int(sample['source_height'])}U",
            f"#define IRDET_SSD_RAW_SAMPLE_MODEL_WIDTH          {int(sample['model_width'])}U",
            f"#define IRDET_SSD_RAW_SAMPLE_MODEL_HEIGHT         {int(sample['model_height'])}U",
            f"#define IRDET_SSD_RAW_SAMPLE_NUM_ANCHORS          {int(sample['num_anchors'])}U",
            f"#define IRDET_SSD_RAW_SAMPLE_NUM_CLASSES_WITH_BG  {int(sample['num_classes_with_bg'])}U",
            f"#define IRDET_SSD_RAW_SAMPLE_SCORE_THRESH_X1000   {int(sample['score_threshold_x1000'])}U",
            f"#define IRDET_SSD_RAW_SAMPLE_IOU_THRESH_X1000     {int(sample['iou_threshold_x1000'])}U",
            f"#define IRDET_SSD_RAW_SAMPLE_EXPECTED_COUNT       {det_count}U",
            "",
            c_float_array("IRDET_SSD_RAW_SAMPLE_BBOX_REGRESSION", sample["bbox_regression"]),
            "",
            c_float_array("IRDET_SSD_RAW_SAMPLE_CLS_LOGITS", sample["cls_logits"]),
            "",
            c_float_array("IRDET_SSD_RAW_SAMPLE_ANCHORS_XYXY", sample["anchors_xyxy"]),
            "",
            c_u8_array("IRDET_SSD_RAW_SAMPLE_EXPECTED_CLASS_IDS", expected_class_ids),
            c_u16_array("IRDET_SSD_RAW_SAMPLE_EXPECTED_SCORE_X1000", expected_scores),
            c_u16_array("IRDET_SSD_RAW_SAMPLE_EXPECTED_BBOX_XYXY", expected_boxes),
            "",
        ]
    )
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> int:
    configure_console_encoding()
    args = parse_args()
    torch, batched_nms = require_torch_stack()
    device = pick_device(torch, args.device)
    model, class_names, cfg = load_model(args, device)
    score_thresh = float(cfg["score_thresh"]) if args.score_thresh is None else float(args.score_thresh)
    nms_thresh = float(cfg["nms_thresh"]) if args.nms_thresh is None else float(args.nms_thresh)

    dataset = FlirCocoDetectionDataset(
        manifest_path=args.manifest,
        split=args.split,
        training=False,
    )
    if args.index < 0 or args.index >= len(dataset):
        raise IndexError(f"Dataset index out of range: {args.index}, dataset size={len(dataset)}")

    image, target = dataset[args.index]
    image = image.to(device)
    with torch.no_grad():
        bbox_regression, cls_logits, anchors, transformed_size = run_raw_head(model, image)
        transformed_height, transformed_width = transformed_size
        raw_output = raw_postprocess(
            torch=torch,
            batched_nms=batched_nms,
            bbox_regression=bbox_regression,
            cls_logits=cls_logits,
            anchors_xyxy=anchors,
            input_height=int(transformed_height),
            input_width=int(transformed_width),
            orig_height=int(image.shape[-2]),
            orig_width=int(image.shape[-1]),
            score_thresh=score_thresh,
            nms_thresh=nms_thresh,
            topk_candidates=int(args.topk_candidates),
            detections_per_img=int(args.detections_per_img),
        )

    source_height = int(image.shape[-2])
    source_width = int(image.shape[-1])
    expected = []
    boxes = raw_output["boxes"].detach().cpu()
    scores = raw_output["scores"].detach().cpu()
    labels = raw_output["labels"].detach().cpu()
    for box, score, label in zip(boxes, scores, labels):
        class_id = int(label.item()) - 1
        expected.append(
            {
                "class_id": class_id,
                "class_name": class_names[class_id],
                "score_x1000": round_score_x1000(float(score.item())),
                "bbox_xyxy": [
                    round_box_coord(float(box[0].item()), source_width - 1),
                    round_box_coord(float(box[1].item()), source_height - 1),
                    round_box_coord(float(box[2].item()), source_width - 1),
                    round_box_coord(float(box[3].item()), source_height - 1),
                ],
            }
        )

    sample = {
        "format": "ir_ssd_raw_sample_v1",
        "checkpoint": str(args.checkpoint),
        "manifest": str(args.manifest),
        "split": args.split,
        "index": int(args.index),
        "image_id": int(target["image_id"][0].item()),
        "source_width": source_width,
        "source_height": source_height,
        "model_width": int(transformed_width),
        "model_height": int(transformed_height),
        "num_anchors": int(anchors.shape[0]),
        "num_classes_with_bg": int(cls_logits.shape[-1]),
        "score_threshold": score_thresh,
        "iou_threshold": nms_thresh,
        "score_threshold_x1000": round_score_x1000(score_thresh),
        "iou_threshold_x1000": round_score_x1000(nms_thresh),
        "classes": class_names,
        "bbox_regression": bbox_regression.detach().cpu().numpy().reshape(-1).astype("float32").tolist(),
        "cls_logits": cls_logits.detach().cpu().numpy().reshape(-1).astype("float32").tolist(),
        "anchors_xyxy": anchors.detach().cpu().numpy().reshape(-1).astype("float32").tolist(),
        "expected_detections": expected,
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    json_path = args.output_dir / "ssd_raw_sample.json"
    with json_path.open("w", encoding="utf-8") as fp:
        json.dump({k: v for k, v in sample.items() if k not in {"bbox_regression", "cls_logits", "anchors_xyxy"}}, fp, indent=2, ensure_ascii=False)
        fp.write("\n")
    write_header(args.c_header_out, sample)

    print(f"Exported raw sample image_id={sample['image_id']} index={args.index}")
    print(
        f"source={source_width}x{source_height} model={sample['model_width']}x{sample['model_height']} "
        f"anchors={sample['num_anchors']} classes={sample['num_classes_with_bg']}"
    )
    print(f"expected_detections={len(expected)}")
    for item in expected:
        print(
            f"class={item['class_name']} score={item['score_x1000'] / 1000.0:.3f} "
            f"bbox={item['bbox_xyxy']}"
        )
    print(f"Artifacts: {json_path} {args.c_header_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
