#!/usr/bin/env python3
"""Export one quantized depthwise 3x3 window case for RTL testbench validation."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export one quantized depthwise 3x3 window case.")
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("build/pl_layer_case_depthwise_formal"),
        help="Directory produced by export_depthwise_layer_case.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("build/pl_depthwise_window_case_formal"),
        help="Directory for the quantized window case artifacts.",
    )
    parser.add_argument(
        "--channel",
        type=int,
        default=-1,
        help="Depthwise channel index. Use -1 to auto-pick a representative interior location.",
    )
    parser.add_argument("--y", type=int, default=-1, help="Output Y position. Use -1 with auto-pick.")
    parser.add_argument("--x", type=int, default=-1, help="Output X position. Use -1 with auto-pick.")
    parser.add_argument(
        "--frac-bits",
        type=int,
        default=8,
        help="Fractional bits for symmetric fixed-point quantization.",
    )
    parser.add_argument(
        "--c-header-out",
        type=Path,
        default=None,
        help="Optional PS-side C header output path for board realcase replay.",
    )
    return parser.parse_args()


def require_file(path: Path) -> Path:
    if not path.is_file():
        raise FileNotFoundError(f"Required file not found: {path}")
    return path


def load_arrays(input_dir: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    layer_input = np.load(require_file(input_dir / "layer_input.npy")).astype(np.float32, copy=False)
    weight_fused = np.load(require_file(input_dir / "weight_fused.npy")).astype(np.float32, copy=False)
    bias_fused = np.load(require_file(input_dir / "bias_fused.npy")).astype(np.float32, copy=False)
    golden_bn_out = np.load(require_file(input_dir / "golden_bn_out.npy")).astype(np.float32, copy=False)
    return layer_input, weight_fused, bias_fused, golden_bn_out


def choose_case(golden_bn_out: np.ndarray) -> tuple[int, int, int]:
    if golden_bn_out.ndim != 4 or golden_bn_out.shape[0] != 1:
        raise ValueError(f"Expected golden_bn_out shape [1, C, H, W], got {golden_bn_out.shape}")

    _, channels, height, width = golden_bn_out.shape
    if height > 2 and width > 2:
        abs_map = np.abs(golden_bn_out[0, :, 1:-1, 1:-1])
        flat_idx = int(np.argmax(abs_map))
        channel, y_inner, x_inner = np.unravel_index(flat_idx, abs_map.shape)
        return int(channel), int(y_inner + 1), int(x_inner + 1)

    abs_map = np.abs(golden_bn_out[0])
    flat_idx = int(np.argmax(abs_map))
    channel, y_pos, x_pos = np.unravel_index(flat_idx, abs_map.shape)
    return int(channel), int(y_pos), int(x_pos)


def extract_window(layer_input: np.ndarray, channel: int, y_pos: int, x_pos: int) -> np.ndarray:
    _, channels, height, width = layer_input.shape
    if not (0 <= channel < channels):
        raise IndexError(f"Channel out of range: {channel}, channels={channels}")
    if not (0 <= y_pos < height and 0 <= x_pos < width):
        raise IndexError(f"Location out of range: y={y_pos}, x={x_pos}, shape={height}x{width}")

    window = np.zeros((3, 3), dtype=np.float32)
    for ky in range(3):
        for kx in range(3):
            src_y = y_pos + ky - 1
            src_x = x_pos + kx - 1
            if 0 <= src_y < height and 0 <= src_x < width:
                window[ky, kx] = layer_input[0, channel, src_y, src_x]
    return window


def quantize_symmetric(array: np.ndarray, scale: int) -> np.ndarray:
    return np.rint(array * scale).astype(np.int64)


def to_sv_signed(value: int, width: int) -> str:
    intval = int(value)
    if intval < 0:
        return f"-{width}'sd{abs(intval)}"
    return f"{width}'sd{intval}"


def write_c_header(path: Path, artifact: dict) -> None:
    window_q = [int(v) for v in artifact["window_q"]]
    weight_q = [int(v) for v in artifact["weight_q"]]

    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "/*",
        " * Auto-generated by pc/scripts/export_depthwise_window_case.py.",
        " * Source artifact: build/pl_depthwise_window_case_formal/depthwise_window_case.json",
        " *",
        " * Fixed-point format:",
        " * - window_q and weight_q use Q8 scale, value_float ~= q / 256.",
        " * - bias_q and expected_acc use Q16 scale, value_float ~= acc / 65536.",
        " */",
        f"#define IRDET_DW3X3_REALCASE_CHANNEL       {int(artifact['channel'])}",
        f"#define IRDET_DW3X3_REALCASE_Y             {int(artifact['y'])}",
        f"#define IRDET_DW3X3_REALCASE_X             {int(artifact['x'])}",
        f"#define IRDET_DW3X3_REALCASE_FRAC_BITS     {int(artifact['frac_bits'])}",
        f"#define IRDET_DW3X3_REALCASE_INPUT_SCALE   {int(artifact['input_scale'])}",
        f"#define IRDET_DW3X3_REALCASE_ACC_SCALE     {int(artifact['acc_scale'])}",
        f"#define IRDET_DW3X3_REALCASE_BIAS_Q        {int(artifact['bias_q'])}",
        f"#define IRDET_DW3X3_REALCASE_EXPECTED_ACC  ({int(artifact['expected_acc'])})",
        "",
        "static const int16_t IRDET_DW3X3_REALCASE_WINDOW_Q[9] = {",
        f"    {window_q[0]}, {window_q[1]}, {window_q[2]},",
        f"    {window_q[3]}, {window_q[4]}, {window_q[5]},",
        f"    {window_q[6]}, {window_q[7]}, {window_q[8]},",
        "};",
        "",
        "static const int16_t IRDET_DW3X3_REALCASE_WEIGHT_Q[9] = {",
        f"    {weight_q[0]}, {weight_q[1]}, {weight_q[2]},",
        f"    {weight_q[3]}, {weight_q[4]}, {weight_q[5]},",
        f"    {weight_q[6]}, {weight_q[7]}, {weight_q[8]},",
        "};",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    layer_input, weight_fused, bias_fused, golden_bn_out = load_arrays(args.input_dir)

    if args.channel < 0 or args.y < 0 or args.x < 0:
        channel, y_pos, x_pos = choose_case(golden_bn_out)
    else:
        channel = int(args.channel)
        y_pos = int(args.y)
        x_pos = int(args.x)

    frac_bits = int(args.frac_bits)
    if frac_bits < 0 or frac_bits > 12:
        raise ValueError(f"frac_bits must be in [0, 12], got {frac_bits}")

    input_scale = 1 << frac_bits
    acc_scale = input_scale * input_scale

    window_f32 = extract_window(layer_input, channel, y_pos, x_pos)
    weight_f32 = weight_fused[channel, 0]
    bias_f32 = float(bias_fused[channel])
    golden_f32 = float(golden_bn_out[0, channel, y_pos, x_pos])
    direct_float = float(np.sum(window_f32 * weight_f32) + bias_f32)

    window_q = quantize_symmetric(window_f32, input_scale)
    weight_q = quantize_symmetric(weight_f32, input_scale)
    bias_q = int(np.rint(bias_f32 * acc_scale))
    expected_acc = int(np.sum(window_q * weight_q) + bias_q)
    quantized_float = float(expected_acc) / float(acc_scale)

    quant_error = quantized_float - golden_f32
    direct_error = direct_float - golden_f32

    args.output_dir.mkdir(parents=True, exist_ok=True)

    artifact = {
        "case_version": 1,
        "source_dir": str(args.input_dir),
        "channel": channel,
        "y": y_pos,
        "x": x_pos,
        "frac_bits": frac_bits,
        "input_scale": input_scale,
        "acc_scale": acc_scale,
        "window_float": window_f32.reshape(-1).tolist(),
        "weight_float": weight_f32.reshape(-1).tolist(),
        "bias_float": bias_f32,
        "golden_bn_out_float": golden_f32,
        "direct_float": direct_float,
        "quantized_float": quantized_float,
        "direct_error": direct_error,
        "quant_error": quant_error,
        "window_q": window_q.reshape(-1).astype(int).tolist(),
        "weight_q": weight_q.reshape(-1).astype(int).tolist(),
        "bias_q": bias_q,
        "expected_acc": expected_acc,
    }

    json_path = args.output_dir / "depthwise_window_case.json"
    json_path.write_text(json.dumps(artifact, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    svh_lines = [
        "// Auto-generated by pc/scripts/export_depthwise_window_case.py",
        f"`define DW_CASE_CHANNEL {channel}",
        f"`define DW_CASE_Y {y_pos}",
        f"`define DW_CASE_X {x_pos}",
        f"`define DW_CASE_FRAC_BITS {frac_bits}",
        f"`define DW_CASE_INPUT_SCALE {input_scale}",
        f"`define DW_CASE_ACC_SCALE {acc_scale}",
        f"`define DW_CASE_BIAS {to_sv_signed(bias_q, 32)}",
        f"`define DW_CASE_EXPECTED_ACC {to_sv_signed(expected_acc, 32)}",
        f"`define DW_CASE_GOLDEN_FLOAT {golden_f32:.8f}",
        f"`define DW_CASE_DIRECT_FLOAT {direct_float:.8f}",
        f"`define DW_CASE_QUANTIZED_FLOAT {quantized_float:.8f}",
    ]

    for idx, value in enumerate(window_q.reshape(-1).tolist()):
        svh_lines.append(f"`define DW_CASE_PIXEL_{idx} {to_sv_signed(value, 16)}")
    for idx, value in enumerate(weight_q.reshape(-1).tolist()):
        svh_lines.append(f"`define DW_CASE_WEIGHT_{idx} {to_sv_signed(value, 16)}")

    svh_path = args.output_dir / "depthwise_window_case.svh"
    svh_path.write_text("\n".join(svh_lines) + "\n", encoding="utf-8")

    write_c_header(args.output_dir / "depthwise_window_case.h", artifact)
    if args.c_header_out is not None:
        write_c_header(args.c_header_out, artifact)

    summary_lines = [
        f"channel={channel}",
        f"y={y_pos}",
        f"x={x_pos}",
        f"frac_bits={frac_bits}",
        f"golden_bn_out_float={golden_f32:.8f}",
        f"direct_float={direct_float:.8f}",
        f"quantized_float={quantized_float:.8f}",
        f"direct_error={direct_error:.8f}",
        f"quant_error={quant_error:.8f}",
        f"expected_acc={expected_acc}",
        "status=depthwise_window_case_ready",
    ]
    (args.output_dir / "depthwise_window_case.txt").write_text("\n".join(summary_lines) + "\n", encoding="utf-8")

    print(f"Exported quantized depthwise window case to {args.output_dir}")
    if args.c_header_out is not None:
        print(f"Exported PS C header to {args.c_header_out}")
    print(
        f"case channel={channel} y={y_pos} x={x_pos} frac_bits={frac_bits} "
        f"golden={golden_f32:.8f} quantized={quantized_float:.8f} quant_error={quant_error:.8f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
