#!/usr/bin/env python3
"""Export a small batch of quantized depthwise 3x3 windows for PS/PL replay."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export a depthwise 3x3 window batch.")
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("build/pl_layer_case_depthwise_formal"),
        help="Directory produced by export_depthwise_layer_case.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("build/pl_depthwise_window_batch_formal"),
        help="Directory for batch replay artifacts.",
    )
    parser.add_argument(
        "--c-header-out",
        type=Path,
        default=Path("zynq_ps/include/ir_pl_dw3x3_realcase_batch_data.h"),
        help="PS-side C header output path.",
    )
    parser.add_argument("--channel", type=int, default=11, help="Depthwise channel index.")
    parser.add_argument("--start-y", type=int, default=18, help="Top output Y of the patch.")
    parser.add_argument("--start-x", type=int, default=6, help="Left output X of the patch.")
    parser.add_argument("--patch-h", type=int, default=4, help="Patch height in output windows.")
    parser.add_argument("--patch-w", type=int, default=4, help="Patch width in output windows.")
    parser.add_argument("--frac-bits", type=int, default=8, help="Q format fractional bits.")
    parser.add_argument(
        "--symbol-prefix",
        default="IRDET_DW3X3_BATCH",
        help="C macro/static symbol prefix for the generated header.",
    )
    parser.add_argument(
        "--description",
        default="Replays a small same-channel MobileNetV2 depthwise patch on PL.",
        help="Short description stored in the generated header comment.",
    )
    return parser.parse_args()


def require_file(path: Path) -> Path:
    if not path.is_file():
        raise FileNotFoundError(f"Required file not found: {path}")
    return path


def load_arrays(input_dir: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    layer_input = np.load(require_file(input_dir / "layer_input.npy")).astype(np.float32, copy=False)
    weight_fused = np.load(require_file(input_dir / "weight_fused.npy")).astype(np.float32, copy=False)
    bias_fused = np.load(require_file(input_dir / "bias_fused.npy")).astype(np.float32, copy=False)
    golden_bn_out = np.load(require_file(input_dir / "golden_bn_out.npy")).astype(np.float32, copy=False)
    return layer_input, weight_fused, bias_fused, golden_bn_out


def extract_window(layer_input: np.ndarray, channel: int, y_pos: int, x_pos: int) -> np.ndarray:
    _, channels, height, width = layer_input.shape
    if not (0 <= channel < channels):
        raise IndexError(f"Channel out of range: {channel}, channels={channels}")
    if not (0 <= y_pos < height and 0 <= x_pos < width):
        raise IndexError(f"Location out of range: y={y_pos}, x={x_pos}, shape={height}x{width}")

    window = np.zeros((3, 3), dtype=np.float32)
    for ky in range(3):
        for kx in range(3):
            src_y = y_pos + ky - 1
            src_x = x_pos + kx - 1
            if 0 <= src_y < height and 0 <= src_x < width:
                window[ky, kx] = layer_input[0, channel, src_y, src_x]
    return window


def quantize_symmetric(array: np.ndarray, scale: int) -> np.ndarray:
    return np.rint(array * scale).astype(np.int64)


def c_int(value: int) -> str:
    value = int(value)
    if value < 0:
        return f"({value})"
    return str(value)


def write_c_header(path: Path, artifact: dict) -> None:
    cases = artifact["cases"]
    weights = [int(v) for v in artifact["weight_q"]]
    prefix = str(artifact["symbol_prefix"])

    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "/*",
        " * Auto-generated by pc/scripts/export_depthwise_window_batch.py.",
        f" * {artifact['description']}",
        " */",
        f"#define {prefix}_CHANNEL      {int(artifact['channel'])}",
        f"#define {prefix}_START_Y      {int(artifact['start_y'])}",
        f"#define {prefix}_START_X      {int(artifact['start_x'])}",
        f"#define {prefix}_PATCH_H      {int(artifact['patch_h'])}",
        f"#define {prefix}_PATCH_W      {int(artifact['patch_w'])}",
        f"#define {prefix}_COUNT        {len(cases)}",
        f"#define {prefix}_FRAC_BITS    {int(artifact['frac_bits'])}",
        f"#define {prefix}_INPUT_SCALE  {int(artifact['input_scale'])}",
        f"#define {prefix}_ACC_SCALE    {int(artifact['acc_scale'])}",
        f"#define {prefix}_BIAS_Q       {c_int(int(artifact['bias_q']))}",
        "",
        f"static const int16_t {prefix}_WEIGHT_Q[9] = {{",
        f"    {weights[0]}, {weights[1]}, {weights[2]},",
        f"    {weights[3]}, {weights[4]}, {weights[5]},",
        f"    {weights[6]}, {weights[7]}, {weights[8]},",
        "};",
        "",
        f"static const int16_t {prefix}_WINDOW_Q[{prefix}_COUNT][9] = {{",
    ]
    for case in cases:
        window = [int(v) for v in case["window_q"]]
        lines.extend(
            [
                "    {",
                f"        {window[0]}, {window[1]}, {window[2]},",
                f"        {window[3]}, {window[4]}, {window[5]},",
                f"        {window[6]}, {window[7]}, {window[8]},",
                "    },",
            ]
        )
    lines.extend(["};", ""])

    lines.append(f"static const uint16_t {prefix}_Y[{prefix}_COUNT] = {{")
    lines.append("    " + ", ".join(str(int(case["y"])) for case in cases) + ",")
    lines.extend(["};", ""])

    lines.append(f"static const uint16_t {prefix}_X[{prefix}_COUNT] = {{")
    lines.append("    " + ", ".join(str(int(case["x"])) for case in cases) + ",")
    lines.extend(["};", ""])

    lines.append(f"static const int32_t {prefix}_EXPECTED_ACC[{prefix}_COUNT] = {{")
    lines.append("    " + ", ".join(c_int(int(case["expected_acc"])) for case in cases) + ",")
    lines.extend(["};", ""])

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    layer_input, weight_fused, bias_fused, golden_bn_out = load_arrays(args.input_dir)

    if args.frac_bits < 0 or args.frac_bits > 12:
        raise ValueError(f"frac_bits must be in [0, 12], got {args.frac_bits}")
    if args.patch_h <= 0 or args.patch_w <= 0:
        raise ValueError("patch dimensions must be positive")

    _, channels, height, width = golden_bn_out.shape
    if not (0 <= args.channel < channels):
        raise IndexError(f"Channel out of range: {args.channel}, channels={channels}")
    if args.start_y < 0 or args.start_x < 0:
        raise IndexError("Patch start must be non-negative")
    if args.start_y + args.patch_h > height or args.start_x + args.patch_w > width:
        raise IndexError(
            f"Patch out of range: start=({args.start_y},{args.start_x}) "
            f"patch={args.patch_h}x{args.patch_w} output_shape={height}x{width}"
        )

    input_scale = 1 << args.frac_bits
    acc_scale = input_scale * input_scale
    weight_f32 = weight_fused[args.channel, 0]
    weight_q = quantize_symmetric(weight_f32, input_scale)
    bias_f32 = float(bias_fused[args.channel])
    bias_q = int(np.rint(bias_f32 * acc_scale))

    cases = []
    for py in range(args.patch_h):
        for px in range(args.patch_w):
            y_pos = args.start_y + py
            x_pos = args.start_x + px
            window_f32 = extract_window(layer_input, args.channel, y_pos, x_pos)
            window_q = quantize_symmetric(window_f32, input_scale)
            expected_acc = int(np.sum(window_q * weight_q) + bias_q)
            quantized_float = float(expected_acc) / float(acc_scale)
            golden_f32 = float(golden_bn_out[0, args.channel, y_pos, x_pos])
            cases.append(
                {
                    "index": len(cases),
                    "y": int(y_pos),
                    "x": int(x_pos),
                    "window_q": window_q.reshape(-1).astype(int).tolist(),
                    "expected_acc": int(expected_acc),
                    "golden_bn_out_float": golden_f32,
                    "quantized_float": quantized_float,
                    "quant_error": quantized_float - golden_f32,
                }
            )

    artifact = {
        "case_version": 1,
        "source_dir": str(args.input_dir),
        "channel": int(args.channel),
        "start_y": int(args.start_y),
        "start_x": int(args.start_x),
        "patch_h": int(args.patch_h),
        "patch_w": int(args.patch_w),
        "frac_bits": int(args.frac_bits),
        "input_scale": int(input_scale),
        "acc_scale": int(acc_scale),
        "weight_q": weight_q.reshape(-1).astype(int).tolist(),
        "bias_q": int(bias_q),
        "symbol_prefix": args.symbol_prefix,
        "description": args.description,
        "cases": cases,
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    json_path = args.output_dir / "depthwise_window_batch.json"
    json_path.write_text(json.dumps(artifact, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    write_c_header(args.output_dir / "depthwise_window_batch.h", artifact)
    write_c_header(args.c_header_out, artifact)

    max_abs_err = max(abs(float(case["quant_error"])) for case in cases)
    summary = [
        f"channel={args.channel}",
        f"start_y={args.start_y}",
        f"start_x={args.start_x}",
        f"patch_h={args.patch_h}",
        f"patch_w={args.patch_w}",
        f"count={len(cases)}",
        f"frac_bits={args.frac_bits}",
        f"max_abs_quant_error={max_abs_err:.8f}",
        "status=depthwise_window_batch_ready",
    ]
    (args.output_dir / "depthwise_window_batch.txt").write_text("\n".join(summary) + "\n", encoding="utf-8")

    print(f"Exported depthwise window batch to {args.output_dir}")
    print(f"Exported PS C header to {args.c_header_out}")
    print(
        f"batch channel={args.channel} start=({args.start_y},{args.start_x}) "
        f"patch={args.patch_h}x{args.patch_w} count={len(cases)} max_abs_quant_error={max_abs_err:.8f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
