#!/usr/bin/env python3
"""Export one quantized depthwise channel for PL full-channel scheduler validation."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export one full depthwise channel for PS/PL validation.")
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("build/pl_layer_case_depthwise_formal"),
        help="Directory produced by export_depthwise_layer_case.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("build/pl_depthwise_full_channel_formal"),
        help="Directory for full-channel artifacts.",
    )
    parser.add_argument(
        "--c-header-out",
        type=Path,
        default=Path("zynq_ps/include/ir_pl_dw3x3_full_channel_data.h"),
        help="PS-side C header output path.",
    )
    parser.add_argument("--channel", type=int, default=11, help="Depthwise channel index.")
    parser.add_argument("--frac-bits", type=int, default=8, help="Q format fractional bits.")
    return parser.parse_args()


def require_file(path: Path) -> Path:
    if not path.is_file():
        raise FileNotFoundError(f"Required file not found: {path}")
    return path


def load_arrays(input_dir: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    layer_input = np.load(require_file(input_dir / "layer_input.npy")).astype(np.float32, copy=False)
    weight_fused = np.load(require_file(input_dir / "weight_fused.npy")).astype(np.float32, copy=False)
    bias_fused = np.load(require_file(input_dir / "bias_fused.npy")).astype(np.float32, copy=False)
    golden_bn_out = np.load(require_file(input_dir / "golden_bn_out.npy")).astype(np.float32, copy=False)
    return layer_input, weight_fused, bias_fused, golden_bn_out


def quantize_symmetric(array: np.ndarray, scale: int) -> np.ndarray:
    return np.rint(array * scale).astype(np.int64)


def c_int(value: int) -> str:
    value = int(value)
    if value < 0:
        return f"({value})"
    return str(value)


def expected_at(input_q: np.ndarray, weight_q: np.ndarray, bias_q: int, y_pos: int, x_pos: int) -> int:
    height, width = input_q.shape
    acc = int(bias_q)
    tap = 0
    for ky in range(-1, 2):
        for kx in range(-1, 2):
            src_y = y_pos + ky
            src_x = x_pos + kx
            if 0 <= src_y < height and 0 <= src_x < width:
                acc += int(input_q[src_y, src_x]) * int(weight_q.reshape(-1)[tap])
            tap += 1
    return acc


def write_array(lines: list[str], values: list[int], c_type: str, name: str, per_line: int = 12) -> None:
    lines.append(f"static const {c_type} {name}[{len(values)}] = {{")
    for start in range(0, len(values), per_line):
        chunk = values[start : start + per_line]
        lines.append("    " + ", ".join(c_int(v) for v in chunk) + ",")
    lines.extend(["};", ""])


def write_c_header(path: Path, artifact: dict) -> None:
    prefix = "IRDET_DW3X3_FULL_CH"
    input_q = [int(v) for v in artifact["input_q"]]
    weight_q = [int(v) for v in artifact["weight_q"]]
    expected_acc = [int(v) for v in artifact["expected_acc"]]

    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "/*",
        " * Auto-generated by pc/scripts/export_depthwise_full_channel.py.",
        " * Data for the PL full-channel scheduler validation.",
        " */",
        f"#define {prefix}_CHANNEL      {int(artifact['channel'])}",
        f"#define {prefix}_HEIGHT       {int(artifact['height'])}",
        f"#define {prefix}_WIDTH        {int(artifact['width'])}",
        f"#define {prefix}_COUNT        {int(artifact['count'])}",
        f"#define {prefix}_FRAC_BITS    {int(artifact['frac_bits'])}",
        f"#define {prefix}_INPUT_SCALE  {int(artifact['input_scale'])}",
        f"#define {prefix}_ACC_SCALE    {int(artifact['acc_scale'])}",
        f"#define {prefix}_BIAS_Q       {c_int(int(artifact['bias_q']))}",
        "",
    ]
    write_array(lines, weight_q, "int16_t", f"{prefix}_WEIGHT_Q", per_line=9)
    write_array(lines, input_q, "int16_t", f"{prefix}_INPUT_Q", per_line=16)
    write_array(lines, expected_acc, "int32_t", f"{prefix}_EXPECTED_ACC", per_line=8)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    layer_input, weight_fused, bias_fused, golden_bn_out = load_arrays(args.input_dir)

    if args.frac_bits < 0 or args.frac_bits > 12:
        raise ValueError(f"frac_bits must be in [0, 12], got {args.frac_bits}")

    _, channels, height, width = layer_input.shape
    if not (0 <= args.channel < channels):
        raise IndexError(f"Channel out of range: {args.channel}, channels={channels}")

    input_scale = 1 << args.frac_bits
    acc_scale = input_scale * input_scale
    input_q = quantize_symmetric(layer_input[0, args.channel], input_scale)
    weight_q = quantize_symmetric(weight_fused[args.channel, 0], input_scale)
    bias_q = int(np.rint(float(bias_fused[args.channel]) * acc_scale))

    expected = []
    quant_errors = []
    for y_pos in range(height):
        for x_pos in range(width):
            acc = expected_at(input_q, weight_q, bias_q, y_pos, x_pos)
            expected.append(acc)
            quantized_float = float(acc) / float(acc_scale)
            golden = float(golden_bn_out[0, args.channel, y_pos, x_pos])
            quant_errors.append(quantized_float - golden)

    artifact = {
        "case_version": 1,
        "source_dir": str(args.input_dir),
        "channel": int(args.channel),
        "height": int(height),
        "width": int(width),
        "count": int(height * width),
        "frac_bits": int(args.frac_bits),
        "input_scale": int(input_scale),
        "acc_scale": int(acc_scale),
        "bias_q": int(bias_q),
        "input_q": input_q.reshape(-1).astype(int).tolist(),
        "weight_q": weight_q.reshape(-1).astype(int).tolist(),
        "expected_acc": expected,
        "max_abs_quant_error": float(np.max(np.abs(np.array(quant_errors, dtype=np.float32)))),
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "depthwise_full_channel.json").write_text(
        json.dumps(artifact, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    write_c_header(args.output_dir / "depthwise_full_channel.h", artifact)
    write_c_header(args.c_header_out, artifact)

    summary = [
        f"channel={args.channel}",
        f"height={height}",
        f"width={width}",
        f"count={height * width}",
        f"frac_bits={args.frac_bits}",
        f"first_acc={expected[0]}",
        f"last_acc={expected[-1]}",
        f"max_abs_quant_error={artifact['max_abs_quant_error']:.8f}",
        "status=depthwise_full_channel_ready",
    ]
    (args.output_dir / "depthwise_full_channel.txt").write_text("\n".join(summary) + "\n", encoding="utf-8")

    print(f"Exported full depthwise channel to {args.output_dir}")
    print(f"Exported PS C header to {args.c_header_out}")
    print(
        f"channel={args.channel} shape={height}x{width} count={height * width} "
        f"first_acc={expected[0]} last_acc={expected[-1]} "
        f"max_abs_quant_error={artifact['max_abs_quant_error']:.8f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
