#pragma once

#include <stdint.h>

/*
 * Auto-generated by pc/scripts/export_depthwise_window_batch.py.
 * Replays a small same-channel MobileNetV2 depthwise patch on PL.
 */
#define IRDET_DW3X3_BATCH_CHANNEL      11
#define IRDET_DW3X3_BATCH_START_Y      18
#define IRDET_DW3X3_BATCH_START_X      6
#define IRDET_DW3X3_BATCH_PATCH_H      4
#define IRDET_DW3X3_BATCH_PATCH_W      4
#define IRDET_DW3X3_BATCH_COUNT        16
#define IRDET_DW3X3_BATCH_FRAC_BITS    8
#define IRDET_DW3X3_BATCH_INPUT_SCALE  256
#define IRDET_DW3X3_BATCH_ACC_SCALE    65536
#define IRDET_DW3X3_BATCH_BIAS_Q       1189

static const int16_t IRDET_DW3X3_BATCH_WEIGHT_Q[9] = {
    79, 190, 77,
    -466, -241, -588,
    123, 550, 360,
};

static const int16_t IRDET_DW3X3_BATCH_WINDOW_Q[IRDET_DW3X3_BATCH_COUNT][9] = {
    {
        98, 35, 97,
        188, 111, 77,
        141, 203, 54,
    },
    {
        35, 97, 131,
        111, 77, 161,
        203, 54, 237,
    },
    {
        97, 131, 64,
        77, 161, 74,
        54, 237, 4,
    },
    {
        131, 64, 42,
        161, 74, 14,
        237, 4, 0,
    },
    {
        188, 111, 77,
        141, 203, 54,
        46, 37, 16,
    },
    {
        111, 77, 161,
        203, 54, 237,
        37, 16, 44,
    },
    {
        77, 161, 74,
        54, 237, 4,
        16, 44, 3,
    },
    {
        161, 74, 14,
        237, 4, 0,
        44, 3, 20,
    },
    {
        141, 203, 54,
        46, 37, 16,
        32, 47, 37,
    },
    {
        203, 54, 237,
        37, 16, 44,
        47, 37, 17,
    },
    {
        54, 237, 4,
        16, 44, 3,
        37, 17, 16,
    },
    {
        237, 4, 0,
        44, 3, 20,
        17, 16, 27,
    },
    {
        46, 37, 16,
        32, 47, 37,
        38, 41, 33,
    },
    {
        37, 16, 44,
        47, 37, 17,
        41, 33, 26,
    },
    {
        16, 44, 3,
        37, 17, 16,
        33, 26, 53,
    },
    {
        44, 3, 20,
        17, 16, 27,
        26, 53, 42,
    },
};

static const uint16_t IRDET_DW3X3_BATCH_Y[IRDET_DW3X3_BATCH_COUNT] = {
    18, 18, 18, 18, 19, 19, 19, 19, 20, 20, 20, 20, 21, 21, 21, 21,
};

static const uint16_t IRDET_DW3X3_BATCH_X[IRDET_DW3X3_BATCH_COUNT] = {
    6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9, 6, 7, 8, 9,
};

static const int32_t IRDET_DW3X3_BATCH_EXPECTED_ACC[IRDET_DW3X3_BATCH_COUNT] = {
    11848, 7509, 58907, (-42809), (-71553), (-180792), (-13825), (-68098), 58401, 31016, 50630, 8296, 4194, 2278, 17736, 26589,
};
