#pragma once

#include <stdint.h>

/*
 * Auto-generated by pc/scripts/export_depthwise_window_case.py.
 * Source artifact: build/pl_depthwise_window_case_formal/depthwise_window_case.json
 *
 * Fixed-point format:
 * - window_q and weight_q use Q8 scale, value_float ~= q / 256.
 * - bias_q and expected_acc use Q16 scale, value_float ~= acc / 65536.
 */
#define IRDET_DW3X3_REALCASE_CHANNEL       11
#define IRDET_DW3X3_REALCASE_Y             19
#define IRDET_DW3X3_REALCASE_X             7
#define IRDET_DW3X3_REALCASE_FRAC_BITS     8
#define IRDET_DW3X3_REALCASE_INPUT_SCALE   256
#define IRDET_DW3X3_REALCASE_ACC_SCALE     65536
#define IRDET_DW3X3_REALCASE_BIAS_Q        1189
#define IRDET_DW3X3_REALCASE_EXPECTED_ACC  (-180792)

static const int16_t IRDET_DW3X3_REALCASE_WINDOW_Q[9] = {
    111, 77, 161,
    203, 54, 237,
    37, 16, 44,
};

static const int16_t IRDET_DW3X3_REALCASE_WEIGHT_Q[9] = {
    79, 190, 77,
    -466, -241, -588,
    123, 550, 360,
};
